global using CG.Blazor.Themes;
global using CG.Green.Directors;
global using CG.Validations;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.RazorPages;
global using MudBlazor;
global using MudBlazor.Services;
global using System.Diagnostics;
