//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CG.Green.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CG.Green.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute Refresh Token Lifetime.
        /// </summary>
        internal static string AbsoluteRefreshTokenLifetime {
            get {
                return ResourceManager.GetString("AbsoluteRefreshTokenLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Failed Count.
        /// </summary>
        internal static string AccessFailedCount {
            get {
                return ResourceManager.GetString("AccessFailedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Token Lifetime.
        /// </summary>
        internal static string AccessTokenLifetime {
            get {
                return ResourceManager.GetString("AccessTokenLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Token Type.
        /// </summary>
        internal static string AccessTokenType {
            get {
                return ResourceManager.GetString("AccessTokenType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Access Tokens Via Browser.
        /// </summary>
        internal static string AllowAccessTokensViaBrowser {
            get {
                return ResourceManager.GetString("AllowAccessTokensViaBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed CORS Origins.
        /// </summary>
        internal static string AllowedCORSOrigins {
            get {
                return ResourceManager.GetString("AllowedCORSOrigins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Grant Types.
        /// </summary>
        internal static string AllowedGrantTypes {
            get {
                return ResourceManager.GetString("AllowedGrantTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Identity Token Signing Algorithms.
        /// </summary>
        internal static string AllowedIdentityTokenSigningAlgorithms {
            get {
                return ResourceManager.GetString("AllowedIdentityTokenSigningAlgorithms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Scopes.
        /// </summary>
        internal static string AllowedScopes {
            get {
                return ResourceManager.GetString("AllowedScopes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Include User Claims In Id Token.
        /// </summary>
        internal static string AllowIncludeUserClaimsInIdToken {
            get {
                return ResourceManager.GetString("AllowIncludeUserClaimsInIdToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Offline Access.
        /// </summary>
        internal static string AllowOfflineAccess {
            get {
                return ResourceManager.GetString("AllowOfflineAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Remember Consent.
        /// </summary>
        internal static string AllowRememberConsent {
            get {
                return ResourceManager.GetString("AllowRememberConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Send Client Claims.
        /// </summary>
        internal static string AllowSendClientClaims {
            get {
                return ResourceManager.GetString("AllowSendClientClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Code Lifetime.
        /// </summary>
        internal static string AuthorizationCodeLifetime {
            get {
                return ResourceManager.GetString("AuthorizationCodeLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Channel Logout Session Required.
        /// </summary>
        internal static string BackChannelLogoutSessionRequired {
            get {
                return ResourceManager.GetString("BackChannelLogoutSessionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Channel Logout URI.
        /// </summary>
        internal static string BackChannelLogoutURI {
            get {
                return ResourceManager.GetString("BackChannelLogoutURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIBA Lifetime.
        /// </summary>
        internal static string CIBALifetime {
            get {
                return ResourceManager.GetString("CIBALifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claims.
        /// </summary>
        internal static string Claims {
            get {
                return ResourceManager.GetString("Claims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Claims Prefix.
        /// </summary>
        internal static string ClientClaimsPrefix {
            get {
                return ResourceManager.GetString("ClientClaimsPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Id.
        /// </summary>
        internal static string ClientId {
            get {
                return ResourceManager.GetString("ClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name.
        /// </summary>
        internal static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Secrets.
        /// </summary>
        internal static string ClientSecrets {
            get {
                return ResourceManager.GetString("ClientSecrets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client URI.
        /// </summary>
        internal static string ClientURI {
            get {
                return ResourceManager.GetString("ClientURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        internal static string ConfirmPasswordError {
            get {
                return ResourceManager.GetString("ConfirmPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consent Lifetime.
        /// </summary>
        internal static string ConsentLifetime {
            get {
                return ResourceManager.GetString("ConsentLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate Lifetime with User Session.
        /// </summary>
        internal static string CoordinateLifetimeWithUserSession {
            get {
                return ResourceManager.GetString("CoordinateLifetimeWithUserSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Code Lifetime.
        /// </summary>
        internal static string DeviceCodeLifetime {
            get {
                return ResourceManager.GetString("DeviceCodeLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Confirmed.
        /// </summary>
        internal static string EmailConfirmed {
            get {
                return ResourceManager.GetString("EmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Local Login.
        /// </summary>
        internal static string EnableLocalLogin {
            get {
                return ResourceManager.GetString("EnableLocalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration.
        /// </summary>
        internal static string Expiration {
            get {
                return ResourceManager.GetString("Expiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Channel Logout Session Required.
        /// </summary>
        internal static string FrontChannelLogoutSessionRequired {
            get {
                return ResourceManager.GetString("FrontChannelLogoutSessionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Channel Logout URI.
        /// </summary>
        internal static string FrontChannelLogoutUri {
            get {
                return ResourceManager.GetString("FrontChannelLogoutUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Provider Restrictions.
        /// </summary>
        internal static string IdentityProviderRestrictions {
            get {
                return ResourceManager.GetString("IdentityProviderRestrictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Token Lifetime.
        /// </summary>
        internal static string IdentityTokenLifetime {
            get {
                return ResourceManager.GetString("IdentityTokenLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include JWT Id.
        /// </summary>
        internal static string IncludeJWTId {
            get {
                return ResourceManager.GetString("IncludeJWTId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Hashed.
        /// </summary>
        internal static string IsHashed {
            get {
                return ResourceManager.GetString("IsHashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} and at max {1} characters long..
        /// </summary>
        internal static string LengthError {
            get {
                return ResourceManager.GetString("LengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockout Enabled.
        /// </summary>
        internal static string LockoutEnabled {
            get {
                return ResourceManager.GetString("LockoutEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockout End.
        /// </summary>
        internal static string LockoutEnd {
            get {
                return ResourceManager.GetString("LockoutEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo URI.
        /// </summary>
        internal static string LogoURI {
            get {
                return ResourceManager.GetString("LogoURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pair Wise Subject Salt.
        /// </summary>
        internal static string PairWiseSubjectSalt {
            get {
                return ResourceManager.GetString("PairWiseSubjectSalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must have at least one uppercase (&apos;A&apos;-&apos;Z&apos;)..
        /// </summary>
        internal static string PasswordCaseError {
            get {
                return ResourceManager.GetString("PasswordCaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must have at least one digit (&apos;0&apos;-&apos;9&apos;)..
        /// </summary>
        internal static string PasswordDigitsError {
            get {
                return ResourceManager.GetString("PasswordDigitsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must have at least one non alphanumeric character..
        /// </summary>
        internal static string PasswordNonAlphaError {
            get {
                return ResourceManager.GetString("PasswordNonAlphaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polling Interval.
        /// </summary>
        internal static string PollingInterval {
            get {
                return ResourceManager.GetString("PollingInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Logout URIs.
        /// </summary>
        internal static string PostLogoutUris {
            get {
                return ResourceManager.GetString("PostLogoutUris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol Type.
        /// </summary>
        internal static string ProtocolType {
            get {
                return ResourceManager.GetString("ProtocolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect URIs.
        /// </summary>
        internal static string RedirectUris {
            get {
                return ResourceManager.GetString("RedirectUris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Token Expiration.
        /// </summary>
        internal static string RefreshTokenExpiration {
            get {
                return ResourceManager.GetString("RefreshTokenExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Token Usage.
        /// </summary>
        internal static string RefreshTokenUsage {
            get {
                return ResourceManager.GetString("RefreshTokenUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require Client Secret.
        /// </summary>
        internal static string RequireClientSecret {
            get {
                return ResourceManager.GetString("RequireClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require Consent.
        /// </summary>
        internal static string RequireConsent {
            get {
                return ResourceManager.GetString("RequireConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Request Object.
        /// </summary>
        internal static string RequiredRequestObject {
            get {
                return ResourceManager.GetString("RequiredRequestObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require PKCE.
        /// </summary>
        internal static string RequirePKCE {
            get {
                return ResourceManager.GetString("RequirePKCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sliding Refresh Token Lifetime.
        /// </summary>
        internal static string SlidingRefreshTokenLifetime {
            get {
                return ResourceManager.GetString("SlidingRefreshTokenLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Factor Enabled.
        /// </summary>
        internal static string TwoFactorEnabled {
            get {
                return ResourceManager.GetString("TwoFactorEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Access Token Claims on Refresh.
        /// </summary>
        internal static string UpdateAccessTokenClaimsOnRefresh {
            get {
                return ResourceManager.GetString("UpdateAccessTokenClaimsOnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Code Type.
        /// </summary>
        internal static string UserCodeType {
            get {
                return ResourceManager.GetString("UserCodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User SSO Lifetime.
        /// </summary>
        internal static string UserSSOLifetime {
            get {
                return ResourceManager.GetString("UserSSOLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
