//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CG.Green.Areas.Admin.Pages.Clients.Panels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CorsPanel_razor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CorsPanel_razor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CG.Green.Areas.Admin.Pages.Clients.Panels.CorsPanel.razor", typeof(CorsPanel_razor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something broke!.
        /// </summary>
        internal static string Broke {
            get {
                return ResourceManager.GetString("Broke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross Original Resource Sharing.
        /// </summary>
        internal static string CORS {
            get {
                return ResourceManager.GetString("CORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create CORS Origin.
        /// </summary>
        internal static string CreateCORS {
            get {
                return ResourceManager.GetString("CreateCORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit CORS Origin.
        /// </summary>
        internal static string EditCORS {
            get {
                return ResourceManager.GetString("EditCORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading CORS.
        /// </summary>
        internal static string LoadingCORS {
            get {
                return ResourceManager.GetString("LoadingCORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No CORS origins were found..
        /// </summary>
        internal static string NoCORS {
            get {
                return ResourceManager.GetString("NoCORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows per page:.
        /// </summary>
        internal static string RowsPerPage {
            get {
                return ResourceManager.GetString("RowsPerPage", resourceCulture);
            }
        }
    }
}
