//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CG.Green.Areas.Admin.Pages.Clients.Panels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MiscPanel_razor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MiscPanel_razor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CG.Green.Areas.Admin.Pages.Clients.Panels.MiscPanel.razor", typeof(MiscPanel_razor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIBA lifetime.
        /// </summary>
        internal static string CibaLifetime {
            get {
                return ResourceManager.GetString("CibaLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backchannel authentication request lifetime, in seconds..
        /// </summary>
        internal static string CibaLifetimeHelp {
            get {
                return ResourceManager.GetString("CibaLifetimeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairwise Subject Salt.
        /// </summary>
        internal static string PairWiseSubjectSalt {
            get {
                return ResourceManager.GetString("PairWiseSubjectSalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A SALT value for generating pairwise subject IDs..
        /// </summary>
        internal static string PairWiseSubjectSaltHelp {
            get {
                return ResourceManager.GetString("PairWiseSubjectSaltHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol Type.
        /// </summary>
        internal static string ProtocolType {
            get {
                return ResourceManager.GetString("ProtocolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The protocol type for the client..
        /// </summary>
        internal static string ProtocolTypeHelp {
            get {
                return ResourceManager.GetString("ProtocolTypeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Code Type.
        /// </summary>
        internal static string UserCodeType {
            get {
                return ResourceManager.GetString("UserCodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of device flow user code.
        /// </summary>
        internal static string UserCodeTypeHelp {
            get {
                return ResourceManager.GetString("UserCodeTypeHelp", resourceCulture);
            }
        }
    }
}
