//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CG.Green.Areas.Admin.Pages.Clients.Panels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsPanel_razor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsPanel_razor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CG.Green.Areas.Admin.Pages.Clients.Panels.SettingsPanel.razor", typeof(SettingsPanel_razor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed GrantTypes.
        /// </summary>
        internal static string AllowedGrantType {
            get {
                return ResourceManager.GetString("AllowedGrantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of grant to use for this client..
        /// </summary>
        internal static string AllowedGrantTypeHelp {
            get {
                return ResourceManager.GetString("AllowedGrantTypeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Scopes.
        /// </summary>
        internal static string AllowedScopes {
            get {
                return ResourceManager.GetString("AllowedScopes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scopes this client will ask for.
        /// </summary>
        internal static string AllowedScopesHelp {
            get {
                return ResourceManager.GetString("AllowedScopesHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Plain Text PKCE.
        /// </summary>
        internal static string AllowPlainTextPkce {
            get {
                return ResourceManager.GetString("AllowPlainTextPkce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow PKCE to be sent in plain text..
        /// </summary>
        internal static string AllowPlainTextPkceHelp {
            get {
                return ResourceManager.GetString("AllowPlainTextPkceHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something broke!.
        /// </summary>
        internal static string Broke {
            get {
                return ResourceManager.GetString("Broke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Description.
        /// </summary>
        internal static string ClientDescription {
            get {
                return ResourceManager.GetString("ClientDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Id.
        /// </summary>
        internal static string ClientId {
            get {
                return ResourceManager.GetString("ClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the value external callers will use to connect to this client..
        /// </summary>
        internal static string ClientIdHelp {
            get {
                return ResourceManager.GetString("ClientIdHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name.
        /// </summary>
        internal static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal name for this client..
        /// </summary>
        internal static string ClientNameHelp {
            get {
                return ResourceManager.GetString("ClientNameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Id copied to the clipboard.
        /// </summary>
        internal static string CopyClipboard {
            get {
                return ResourceManager.GetString("CopyClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Enabled.
        /// </summary>
        internal static string IsEnabled {
            get {
                return ResourceManager.GetString("IsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/disable the client..
        /// </summary>
        internal static string IsEnabledHelp {
            get {
                return ResourceManager.GetString("IsEnabledHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require PKCE.
        /// </summary>
        internal static string RequirePkce {
            get {
                return ResourceManager.GetString("RequirePkce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proof Key for Code Exchange.
        /// </summary>
        internal static string RequirePkceHelp {
            get {
                return ResourceManager.GetString("RequirePkceHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require Request Object.
        /// </summary>
        internal static string RequireRequestObject {
            get {
                return ResourceManager.GetString("RequireRequestObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require signed requests only..
        /// </summary>
        internal static string RequireRequestObjectHelp {
            get {
                return ResourceManager.GetString("RequireRequestObjectHelp", resourceCulture);
            }
        }
    }
}
