//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CG.Green.Areas.Admin.Pages.Clients.Panels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SsoPanel_razor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SsoPanel_razor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CG.Green.Areas.Admin.Pages.Clients.Panels.SsoPanel.razor", typeof(SsoPanel_razor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Channel Logout Session Required.
        /// </summary>
        internal static string FrontChannelLogoutSessionRequired {
            get {
                return ResourceManager.GetString("FrontChannelLogoutSessionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether or not the user&apos;s session id should be sent to the Front Channel Logout URI..
        /// </summary>
        internal static string FrontChannelLogoutSessionRequiredHelp {
            get {
                return ResourceManager.GetString("FrontChannelLogoutSessionRequiredHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Channel Logout URI.
        /// </summary>
        internal static string FrontChannelLogoutUri {
            get {
                return ResourceManager.GetString("FrontChannelLogoutUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The logout URI for HTTP front-channel based logout.
        /// </summary>
        internal static string FrontChannelLogoutUriHelp {
            get {
                return ResourceManager.GetString("FrontChannelLogoutUriHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User SSO Lifetime.
        /// </summary>
        internal static string UserSsoLifetime {
            get {
                return ResourceManager.GetString("UserSsoLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum duration (in seconds) since the last time the user authenticated..
        /// </summary>
        internal static string UserSsoLifetimeHelp {
            get {
                return ResourceManager.GetString("UserSsoLifetimeHelp", resourceCulture);
            }
        }
    }
}
