//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CG.Green.Areas.Admin.Pages.Clients.Panels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TokenPanel_razor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TokenPanel_razor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CG.Green.Areas.Admin.Pages.Clients.Panels.TokenPanel.razor", typeof(TokenPanel_razor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute Refresh Token Lifetime.
        /// </summary>
        internal static string AbsoluteRefreshTokenLifetime {
            get {
                return ResourceManager.GetString("AbsoluteRefreshTokenLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute lifetime of a refresh token in seconds..
        /// </summary>
        internal static string AbsoluteRefreshTokenLifetimeHelp {
            get {
                return ResourceManager.GetString("AbsoluteRefreshTokenLifetimeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Token Lifetime.
        /// </summary>
        internal static string AccessTokenLifetime {
            get {
                return ResourceManager.GetString("AccessTokenLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifetime of an access token in seconds..
        /// </summary>
        internal static string AccessTokenLifetimeHelp {
            get {
                return ResourceManager.GetString("AccessTokenLifetimeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Tokens.
        /// </summary>
        internal static string AccessTokens {
            get {
                return ResourceManager.GetString("AccessTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Token Type.
        /// </summary>
        internal static string AccessTokenType {
            get {
                return ResourceManager.GetString("AccessTokenType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether the access token is a reference token or a self contained JWT token..
        /// </summary>
        internal static string AccessTokenTypeHelp {
            get {
                return ResourceManager.GetString("AccessTokenTypeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow access tokens via browser.
        /// </summary>
        internal static string AllowAccessTokensViaBrowser {
            get {
                return ResourceManager.GetString("AllowAccessTokensViaBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether access tokens are transmitted via the browser, for this client..
        /// </summary>
        internal static string AllowAccessTokensViaBrowserHelp {
            get {
                return ResourceManager.GetString("AllowAccessTokensViaBrowserHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Signing Algorithms.
        /// </summary>
        internal static string AllowedSigningAlgorithms {
            get {
                return ResourceManager.GetString("AllowedSigningAlgorithms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing algorithm for identity token. If empty, will use the Duende default signing algorithm.
        /// </summary>
        internal static string AllowedSigningAlgorithmsHelp {
            get {
                return ResourceManager.GetString("AllowedSigningAlgorithmsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Offline Access.
        /// </summary>
        internal static string AllowOfflineAccess {
            get {
                return ResourceManager.GetString("AllowOfflineAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/disable refresh tokens..
        /// </summary>
        internal static string AllowOfflineAccessHelp {
            get {
                return ResourceManager.GetString("AllowOfflineAccessHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always include user claims in identity token.
        /// </summary>
        internal static string AlwaysIncludeUserClaimsInIdentityToken {
            get {
                return ResourceManager.GetString("AlwaysIncludeUserClaimsInIdentityToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When requesting both an id token and access token, should the user claims always be added to the id token instead of requiring the client to use the userinfo endpoint..
        /// </summary>
        internal static string AlwaysIncludeUserClaimsInIdentityTokenHelp {
            get {
                return ResourceManager.GetString("AlwaysIncludeUserClaimsInIdentityTokenHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something broke!.
        /// </summary>
        internal static string Broke {
            get {
                return ResourceManager.GetString("Broke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate Lifetime with User Session.
        /// </summary>
        internal static string CoordinateLifetimeWithUserSession {
            get {
                return ResourceManager.GetString("CoordinateLifetimeWithUserSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tie the client&apos;s token lifetime to the user&apos;s session lifetime..
        /// </summary>
        internal static string CoordinateLifetimeWithUserSessionHelp {
            get {
                return ResourceManager.GetString("CoordinateLifetimeWithUserSessionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Signing Algorithm.
        /// </summary>
        internal static string CreateSigningAlgorithm {
            get {
                return ResourceManager.GetString("CreateSigningAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Signing Algorithm.
        /// </summary>
        internal static string EditSigningAlgorithm {
            get {
                return ResourceManager.GetString("EditSigningAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Token Lifetime.
        /// </summary>
        internal static string IdentityTokenLifetime {
            get {
                return ResourceManager.GetString("IdentityTokenLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifetime of an identity token in seconds..
        /// </summary>
        internal static string IdentityTokenLifetimeHelp {
            get {
                return ResourceManager.GetString("IdentityTokenLifetimeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Tokens.
        /// </summary>
        internal static string IdentityTokens {
            get {
                return ResourceManager.GetString("IdentityTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading signing algorithms ....
        /// </summary>
        internal static string LoadingSigningAlgorithms {
            get {
                return ResourceManager.GetString("LoadingSigningAlgorithms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No signing algorithms were found..
        /// </summary>
        internal static string NoSigningAlgorithms {
            get {
                return ResourceManager.GetString("NoSigningAlgorithms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Token Expiration.
        /// </summary>
        internal static string RefreshTokenExpiration {
            get {
                return ResourceManager.GetString("RefreshTokenExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute: the refresh token will expire on a fixed point in time. Sliding: when refreshing the token, the lifetime of the refresh token will be renewed..
        /// </summary>
        internal static string RefreshTokenExpirationHelp {
            get {
                return ResourceManager.GetString("RefreshTokenExpirationHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Tokens.
        /// </summary>
        internal static string RefreshTokens {
            get {
                return ResourceManager.GetString("RefreshTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Token Usage.
        /// </summary>
        internal static string RefreshTokenUsage {
            get {
                return ResourceManager.GetString("RefreshTokenUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReUse: the refresh token handle will stay the same when refreshing tokens. OneTime: the refresh token handle will be updated when refreshing tokens..
        /// </summary>
        internal static string RefreshTokenUsageHelp {
            get {
                return ResourceManager.GetString("RefreshTokenUsageHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows per page:.
        /// </summary>
        internal static string RowsPerPage {
            get {
                return ResourceManager.GetString("RowsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sliding Refresh Token Lifetime.
        /// </summary>
        internal static string SlidingRefreshTokenLifetime {
            get {
                return ResourceManager.GetString("SlidingRefreshTokenLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sliding lifetime of a refresh token in seconds..
        /// </summary>
        internal static string SlidingRefreshTokenLifetimeHelp {
            get {
                return ResourceManager.GetString("SlidingRefreshTokenLifetimeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update access token claims on refresh.
        /// </summary>
        internal static string UpdateAccessTokenClaimsOnRefresh {
            get {
                return ResourceManager.GetString("UpdateAccessTokenClaimsOnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether the access token (and its claims) should be updated on a refresh token request.
        /// </summary>
        internal static string UpdateAccessTokenClaimsOnRefreshHelp {
            get {
                return ResourceManager.GetString("UpdateAccessTokenClaimsOnRefreshHelp", resourceCulture);
            }
        }
    }
}
